kamel:
  run:
    integration:
      api-kafka:
        property-files: '[config/application.properties]'
        dependencies: '[camel-rest,camel-undertow]'
      sensor:
        property-files: '[config/application.properties]'
        dependencies: '[camel-elasticsearch-rest, camel-cassandraql, camel-rest, camel-undertow]'
      feed:
        property-files: '[config/application.properties]'
      printer:
        property-files: '[config/application.properties]'
      splitter:
        property-files: '[config/application.properties]'