kamel:
  run:
    integration:
      api-kafka:
        property-files: '[application.properties]'
        dependencies: '[camel-rest,camel-undertow]'
      sensor:
        property-files: '[application.properties]'
        dependencies: '[camel-elasticsearch-rest, camel-cassandraql, camel-rest, camel-undertow]'