apiVersion: sources.eventing.knative.dev/v1alpha1                        
kind: CamelSource                                                        
metadata:                                                                
  name: printer-knative                                            
spec:                                                                    
  source:                                                                
    flow:                                                                
      from:                                                              
        uri: knative:channels/words                                                                   
        steps:
          - log:
              message: "sending ${body} to words channel"
          - to:
              slack:
                channel: knative
                parameters:
                  webhookUrl:  "aqui va el webhook de slack"                  
  sink:                                                                  
    ref:                                                                 
      apiVersion: messaging.knative.dev/v1alpha1                         
      kind: InMemoryChannel                                              
      name: words   