apiVersion: sources.eventing.knative.dev/v1alpha1                        
kind: CamelSource                                                        
metadata:                                                                
  name: splitter-knative                                           
spec:                                                                    
  source:                                                                
    flow:                                                                
      from:                                                              
        uri: knative:channels/messages                                                                   
        steps:                                                           
          - split:
              tokenize:
                  token: " "
          - log:
              message: "sending ${body} to words channel"                                 
  sink:                                                                  
    ref:                                                                 
      apiVersion: messaging.knative.dev/v1alpha1                         
      kind: InMemoryChannel                                              
      name: words   