apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: camel-k-basic-pipeline-run-1
spec:
  pipelineRef:
    name: camel-k-openapi-pipeline
  serviceAccountName: 'camel-k-pipeline'
  resources:
    - name: source-repo
      resourceRef:
        name: camel-k-examples-git