kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-camel-k
  namespace: demo
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - delete
  - update
- apiGroups:
    - camel.apache.org
  resources:
    - "*"
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - configmaps
    - secrets
    - serviceaccounts
    - services
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
    - rolebindings
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
    - replicasets
    - statefulsets
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  attributeRestrictions: null
  resources:
    - daemonsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
    - "build.openshift.io"
  resources:
    - buildconfigs
    - buildconfigs/webhooks
    - builds
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
    - "image.openshift.io"
  resources:
    - imagestreamimages
    - imagestreammappings
    - imagestreams
    - imagestreams/secrets
    - imagestreamtags
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
    - build.openshift.io
  attributeRestrictions: null
  resources:
    - buildconfigs/instantiate
    - buildconfigs/instantiatebinary
    - builds/clone
  verbs:
    - create
- apiGroups:
    - ""
    - "route.openshift.io"
  resources:
    - routes
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
    - route.openshift.io
  resources:
    - routes/custom-host
  verbs:
    - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-camel-k
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-camel-k
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: tekton-camel-k
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-camel-k